### ISSUE TITLE
Generation failed: check_model_inputs.<locals>.wrapped_fn() got an unexpected keyword argument 'inputs_embeds'

### ISSUE THREAD

**Issue by merepapa** [flybirdxx/ComfyUI-Qwen-TTS#18]
FB_Qwen3TTSVoiceClone
Generation failed: check_model_inputs.<locals>.wrapped_fn() got an unexpected keyword argument 'inputs_embeds'

**Comment by flybirdxx** [comment]
Please ensure the code in the file is up to date.

**Comment by cochese9000** [comment]
go into the custom nodes folder and into the qwentts and do a git pull.

**Comment by pazoozoo42** [comment]
Pulled latest version right now, restarted ComfyUI. still getting this error
```
FB_Qwen3TTSVoiceClone
Generation failed: check_model_inputs.<locals>.wrapped_fn() got an unexpected keyword argument 'inputs_embeds'
```

Log: 
```
Jan 24 08:07:02 pop-os python[2580619]: got prompt
Jan 24 08:07:02 pop-os python[2580619]: code_predictor_config is None. Initializing code_predictor model with default values
Jan 24 08:07:02 pop-os python[2580619]: Setting `pad_token_id` to `eos_token_id`:2150 for open-end generation.
Jan 24 08:07:05 pop-os python[2580619]: !!! Exception during processing !!! check_model_inputs.<locals>.wrapped_fn() got an unexpected keyword argument 'inputs_embeds'
Jan 24 08:07:05 pop-os python[2580619]: Traceback (most recent call last):
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/execution.py", line 518, in execute
Jan 24 08:07:05 pop-os python[2580619]:     output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
Jan 24 08:07:05 pop-os python[2580619]:                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/execution.py", line 329, in get_output_data
Jan 24 08:07:05 pop-os python[2580619]:     return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
Jan 24 08:07:05 pop-os python[2580619]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/execution.py", line 303, in _async_map_node_over_list
Jan 24 08:07:05 pop-os python[2580619]:     await process_inputs(input_dict, i)
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/execution.py", line 291, in process_inputs
Jan 24 08:07:05 pop-os python[2580619]:     result = f(**inputs)
Jan 24 08:07:05 pop-os python[2580619]:              ^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/custom_nodes/qwen3-tts-comfyui/nodes.py", line 607, in generate
Jan 24 08:07:05 pop-os python[2580619]:     wavs, sr = model.generate_custom_voice(
Jan 24 08:07:05 pop-os python[2580619]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
Jan 24 08:07:05 pop-os python[2580619]:     return func(*args, **kwargs)
Jan 24 08:07:05 pop-os python[2580619]:            ^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/custom_nodes/qwen3-tts-comfyui/qwen_tts/inference/qwen3_tts_model.py", line 838, in generate_custom_voice
Jan 24 08:07:05 pop-os python[2580619]:     wavs, fs = self.model.speech_tokenizer.decode([{"audio_codes": c} for c in talker_codes_list])
Jan 24 08:07:05 pop-os python[2580619]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/custom_nodes/qwen3-tts-comfyui/qwen_tts/inference/qwen3_tts_tokenizer.py", line 358, in decode
Jan 24 08:07:05 pop-os python[2580619]:     dec = self.model.decode(audio_codes_padded, return_dict=True)
Jan 24 08:07:05 pop-os python[2580619]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/custom_nodes/qwen3-tts-comfyui/qwen_tts/core/tokenizer_12hz/modeling_qwen3_tts_tokenizer_v2.py", line 1029, in decode
Jan 24 08:07:05 pop-os python[2580619]:     audio_values = self.decoder.chunked_decode(audio_codes.transpose(1, 2)).squeeze(1)
Jan 24 08:07:05 pop-os python[2580619]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/custom_nodes/qwen3-tts-comfyui/qwen_tts/core/tokenizer_12hz/modeling_qwen3_tts_tokenizer_v2.py", line 909, in chunked_decode
Jan 24 08:07:05 pop-os python[2580619]:     wav_chunk = self(codes_chunk)
Jan 24 08:07:05 pop-os python[2580619]:                 ^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
Jan 24 08:07:05 pop-os python[2580619]:     return self._call_impl(*args, **kwargs)
Jan 24 08:07:05 pop-os python[2580619]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
Jan 24 08:07:05 pop-os python[2580619]:     return forward_call(*args, **kwargs)
Jan 24 08:07:05 pop-os python[2580619]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/comfy/ComfyUI/custom_nodes/qwen3-tts-comfyui/qwen_tts/core/tokenizer_12hz/modeling_qwen3_tts_tokenizer_v2.py", line 892, in forward
Jan 24 08:07:05 pop-os python[2580619]:     hidden = self.pre_transformer(inputs_embeds=hidden).last_hidden_state
Jan 24 08:07:05 pop-os python[2580619]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
Jan 24 08:07:05 pop-os python[2580619]:     return self._call_impl(*args, **kwargs)
Jan 24 08:07:05 pop-os python[2580619]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]:   File "/home/mk/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
Jan 24 08:07:05 pop-os python[2580619]:     return forward_call(*args, **kwargs)
Jan 24 08:07:05 pop-os python[2580619]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 24 08:07:05 pop-os python[2580619]: TypeError: check_model_inputs.<locals>.wrapped_fn() got an unexpected keyword argument 'inputs_embeds'
Jan 24 08:07:05 pop-os python[2580619]: Prompt executed in 2.75 seconds
```

**Comment by pazoozoo42** [comment]
Fixed after I updated transformers from 4.57.3 to 4.57.6
