### ISSUE TITLE
can not use Transformer > 5.0

### ISSUE THREAD

**Issue by smart0937** [flybirdxx/ComfyUI-Qwen-TTS#101]
I have test transformers==4.57.6 is ok.
but can not use Transformer > 5.0.
希望您有空時能修改讓這個擴展能相容於Transformer > 5.0

**Comment by Skuuurt** [comment]
Hi,

I am seeing the same Transformers 5.x compatibility problem with ComfyUI-Qwen-TTS v1.0.7.

Environment:
- ComfyUI 0.29.2
- Transformers 5.14.1
- Python 3.12.11
- Windows 11
- RTX 4080 SUPER

The model fails to load with:

AttributeError: 'Qwen3TTSTalkerConfig' object has no attribute 'pad_token_id'

After temporarily adding a pad_token_id alias, loading proceeds further but fails with:

KeyError: 'default'

at:

self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

Downgrading Transformers globally is not viable because other ComfyUI custom nodes require Transformers 5.x.

Are you planning to add Transformers 5.x compatibility to the bundled Qwen3-TTS code?

I can provide full logs and test a proposed fix.

Thank you.

**Comment by emiapwil** [comment]
Guys, feel free to try pull request #103 and see if it works on your setup.

**Comment by cgvirus** [comment]
> Guys, feel free to try pull request [#103](https://github.com/flybirdxx/ComfyUI-Qwen-TTS/pull/103) and see if it works on your setup.

It is working with transformer 5.16.1 , Comfyui 0.34.0
